allowBuilds:
  esbuild: true
  unrs-resolver: false
lockfileIncludeTarballUrl: true
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@softarc/*"
  # Renovate security update: esbuild@0.28.1
  - esbuild@0.28.1
