name: Generate code-coverage badge
on:
  push:
    branches:
      - main
jobs:
  generate-badges-on-custom-branch:
    name: Generate badges on the badges branch
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: "24.x"
      - name: Setup PNPM
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 11

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Delete remote badges branch
        run: git push origin --delete badges

      - name: Create badges branch
        run: git checkout -b badges

      - name: Tests
        run: pnpm test-ci

      - name: Generating coverage badges
        uses: jpb06/coverage-badges-action@6bebba3f008cb03c2be0ff9b148c663df30cde4b # v1.4.11
        with:
          branches: "main"
          target-branch: badges

      - name: Push badges branch
        run: git push origin badges
